import { writeFileSync, readFileSync } from 'node:fs';

// 完整的目/科中文映射
const orderMap: Record<string, string> = {
  'Anseriformes': '雁形目',
  'Galliformes': '鸡形目',
  'Podicipitiformes': '鸊鷉目',
  'Podicipediformes': '鸊鷉目',
  'Columbiformes': '鸽形目',
  'Caprimulgiformes': '夜鹰目',
  'Podargiformes': '蟆口鸱目',
  'Apodiformes': '雨燕目',
  'Ralliformes': '鹤形目',
  'Gruiformes': '鹤形目',
  'Charadriiformes': '鸻形目',
  'Phaethontiformes': '鹲形目',
  'Phoenicopteriformes': '红鹳目',
  'Eurypygiformes': '日鳽目',
  'Gaviiformes': '潜鸟目',
  'Procellariiformes': '鹱形目',
  'Sphenisciformes': '企鹅目',
  'Suliformes': '鲣鸟目',
  'Pelecaniformes': '鹈形目',
  'Ciconiiformes': '鹳形目',
  'Accipitriformes': '鹰形目',
  'Bucerotiformes': '犀鸟目',
  'Coraciiformes': '佛法僧目',
  'Piciformes': '鴷形目',
  'Cariamiformes': '叫鹤目',
  'Falconiformes': '隼形目',
  'Psittaciformes': '鹦形目',
  'Passeriformes': '雀形目',
  'Struthioniformes': '鸵鸟目',
  'Casuariiformes': '鹤鸵目',
  'Apterygiformes': '无翼鸟目',
  'Tinamiformes': '美洲鸵目',
  'Otidiformes': '鸨形目',
  'Cuculiformes': '鹃形目',
  'Strigiformes': '鸮形目',
  'Trogoniformes': '咬鹃目',
  'Leptosomiformes': '鵈鹠目',
  'Galbuliformes': '鴷嘴目',
  'Pterocliformes': '沙鸡目',
};

const familyMap: Record<string, string> = {
  'Anatidae (Ducks, Geese, and Waterfowl)': '鸭科',
  'Phasianidae (Pheasants, Grouse, and Allies)': '雉科',
  'Numididae (Guineafowl)': '珠鸡科',
  'Odontophoridae (New World Quail)': '齿鹑科',
  'Cracidae (Guans and Chachalacas)': '凤冠雉科',
  'Podicipitidae (Grebes)': '鸊鷉科',
  'Podicipedidae (Grebes)': '鸊鷉科',
  'Columbidae (Pigeons and Doves)': '鸠鸽科',
  'Caprimulgidae (Nightjars and Allies)': '夜鹰科',
  'Podargidae (Frogmouths)': '蟆口鸱科',
  'Apodidae (Swifts)': '雨燕科',
  'Hemiprocnidae (Treeswifts)': '凤头雨燕科',
  'Rallidae (Rails, Gallinules, and Coots)': '秧鸡科',
  'Gruidae (Cranes)': '鹤科',
  'Charadriidae (Plovers and Lapwings)': '鸻科',
  'Scolopacidae (Sandpipers and Allies)': '鹬科',
  'Laridae (Gulls, Terns, and Skimmers)': '鸥科',
  'Alcidae (Auks, Murres, and Puffins)': '海雀科',
  'Stercorariidae (Skuas and Jaegers)': '贼鸥科',
  'Phaethontidae (Tropicbirds)': '鹲科',
  'Phoenicopteridae (Flamingos)': '红鹳科',
  'Gaviidae (Loons)': '潜鸟科',
  'Procellariidae (Shearwaters and Petrels)': '鹱科',
  'Hydrobatidae (Northern Storm-Petrels)': '海燕科',
  'Oceanitidae (Southern Storm-Petrels)': '海燕科',
  'Diomedeidae (Albatrosses)': '信天翁科',
  'Fregatidae (Frigatebirds)': '军舰鸟科',
  'Sulidae (Boobies and Gannets)': '鲣鸟科',
  'Phalacrocoracidae (Cormorants and Shags)': '鸬鹚科',
  'Anhingidae (Anhingas)': '蛇鹈科',
  'Pelecanidae (Pelicans)': '鹈鹕科',
  'Ardeidae (Herons, Egrets, and Bitterns)': '鹭科',
  'Threskiornithidae (Ibises and Spoonbills)': '朱鹭科',
  'Ciconiidae (Storks)': '鹳科',
  'Pandionidae (Osprey)': '鹗科',
  'Accipitridae (Hawks, Eagles, and Kites)': '鹰科',
  'Bucerotidae (Hornbills)': '犀鸟科',
  'Upupidae (Hoopoes)': '戴胜科',
  'Phoeniculidae (Woodhoopoes)': '林戴胜科',
  'Coraciidae (Rollers)': '佛法僧科',
  'Alcedinidae (Kingfishers)': '翠鸟科',
  'Meropidae (Bee-eaters)': '蜂虎科',
  'Picidae (Woodpeckers)': '啄木鸟科',
  'Megalaimidae (Asian Barbets)': '大拟啄木鸟科',
  'Cariamidae (Seriemas)': '叫鹤科',
  'Falconidae (Falcons and Caracaras)': '隼科',
  'Psittacidae (New World and African Parrots)': '鹦鹉科',
  'Psittaculidae (Old World Parrots)': '长尾鹦鹉科',
  'Cacatuidae (Cockatoos)': '凤头鹦鹉科',
  'Struthionidae (Ostriches)': '鸵鸟科',
  'Casuariidae (Cassowaries and Emu)': '鹤鸵科',
  'Cuculidae (Cuckoos)': '杜鹃科',
  'Otididae (Bustards)': '鸨科',
  'Jacanidae (Jacanas)': '水雉科',
  'Recurvirostridae (Stilts and Avocets)': '反嘴鹬科',
  'Burhinidae (Thick-knees)': '石鸻科',
  'Haematopodidae (Oystercatchers)': '蛎鹬科',
  'Glareolidae (Pratincoles and Coursers)': '燕鸻科',
  'Rostratulidae (Painted-Snipes)': '彩鹬科',
  'Ibidorhynchidae (Ibisbill)': '鹮嘴鹬科',
  'Strigiformes': '鸮科',
  'Scolopacidae': '鹬科',
  'Laniidae (Shrikes)': '伯劳科',
  'Vireonidae (Vireos)': '绿鹃科',
  'Oriolidae (Old World Orioles)': '黄鹂科',
  'Dicruridae (Drongos)': '卷尾科',
  'Monarchidae (Monarch Flycatchers)': '王鹟科',
  'Rhipiduridae (Fantails)': '扇尾鹟科',
  'Artamidae (Woodswallows, Bellmagpies, and Allies)': '丝鸦科',
  'Stenostiridae (Fairy Flycatchers)': '仙莺科',
  'Paridae (Tits, Chickadees, and Titmice)': '山雀科',
  'Remizidae (Penduline-Tits)': '攀雀科',
  'Alaudidae (Larks)': '百灵科',
  'Pycnonotidae (Bulbuls)': '鹎科',
  'Hirundinidae (Swallows)': '燕科',
  'Aegithalidae (Long-tailed Tits)': '长尾山雀科',
  'Sittidae (Nuthatches)': '鳾科',
  'Certhiidae (Treecreepers)': '旋木雀科',
  'Troglodytidae (Wrens)': '鹪鹩科',
  'Polioptilidae (Gnatcatchers)': '蚋莺科',
  'Regulidae (Kinglets)': '戴菊科',
  'Muscicapidae (Old World Flycatchers)': '鹟科',
  'Cettiidae (Bush Warblers and Allies)': '扇尾莺科',
  'Locustellidae (Grassbirds and Allies)': '草莺科',
  'Acrocephalidae (Reed Warblers and Allies)': '苇莺科',
  'Phylloscopidae (Leaf Warblers)': '柳莺科',
  'Sylviidae (Sylviid Warblers)': '莺科',
  'Cisticolidae (Cisticolas and Allies)': '扇尾莺科',
  'Leiothrichidae (Laughingthrushes and Allies)': '噪鹛科',
  'Pellorneidae (Ground Babblers and Allies)': '幽鹛科',
  'Paradoxornithidae (Parrotbills)': '鸦雀科',
  'Panuridae (Bearded Reedling)': '文须雀科',
  'Alaudidae': '百灵科',
  'Nectariniidae (Sunbirds and Spiderhunters)': '太阳鸟科',
  'Dicaeidae (Flowerpeckers)': '啄花鸟科',
  'Irenidae (Fairy-bluebirds)': '和平鸟科',
  'Chloropseidae (Leafbirds)': '叶鹎科',
  'Estrildidae (Waxbills and Allies)': '梅花雀科',
  'Ploceidae (Weavers and Allies)': '织雀科',
  'Passeridae (Old World Sparrows)': '雀科',
  'Motacillidae (Wagtails and Pipits)': '鹡鸰科',
  'Fringillidae (Finches, Euphonias, and Allies)': '燕雀科',
  'Calcariidae (Longspurs and Snow Buntings)': '铁爪鹀科',
  'Emberizidae (Old World Buntings)': '鹀科',
  'Passerellidae (New World Sparrows)': '雀鹀科',
  'Icteridae (Troupials and Allies)': '拟黄鹂科',
  'Sturnidae (Starlings)': '椋鸟科',
  'Bombycillidae (Waxwings)': '太平鸟科',
  'Cinclidae (Dippers)': '河乌科',
  'Prunellidae (Accentors)': '岩鹨科',
  'Muscicapidae': '鹟科',
  'Turdidae (Thrushes)': '鸫科',
  'Elachuridae (Spotted Elachura)': '斑翅鹛科',
  'Pnoepygidae (Cupwings)': '鳞胸鹛科',
  'Campephagidae (Cuckooshrikes)': '山椒鸟科',
  'Eurylaimidae (Asian and Grauer\'s Broadbills)': '阔嘴鸟科',
  'Pittidae (Pittas)': '八色鸫科',
  'Indicatoridae (Honeyguides)': '响蜜鴷科',
  'Aegithinidae (Ioras)': '叶鹎科',
  'Corvidae (Crows, Jays, and Magpies)': '鸦科',
  'Pteroclidae (Sandgrouse)': '沙鸡科',
  'Strigidae (Owls)': '鸮科',
  'Sylviidae (Sylviid Warblers and Allies)': '莺科',
  'Tichodromidae (Wallcreeper)': '旋壁雀科',
  'Timaliidae (Tree-Babblers, Scimitar-Babblers, and Allies)': '林鹛科',
  'Trogonidae (Trogons)': '咬鹃科',
  'Turdidae (Thrushes and Allies)': '鸫科',
  'Turnicidae (Buttonquail)': '三趾鹑科',
  'Tytonidae (Barn-Owls)': '草鸮科',
  "Urocynchramidae (Przevalski's Pinktail)": '朱鹀科',
  'Vangidae (Vangas, Helmetshrikes, and Allies)': '钩嘴鵙科',
  'Viduidae (Whydahs and Indigobirds)': '维达雀科',
  'Vireonidae (Vireos, Shrike-Babblers, and Erpornis)': '绿鹃科',
  'Zosteropidae (White-eyes, Yuhinas, and Allies)': '绣眼鸟科',
};

const genusMap: Record<string, string> = {
  'Dendrocygna': '树鸭属',
  'Anser': '雁属',
  'Branta': '黑雁属',
  'Cygnus': '天鹅属',
  'Tadorna': '麻鸭属',
  'Spatula': '匙嘴鸭属',
  'Mareca': '鸭属',
  'Anas': '鸭属',
  'Aythya': '潜鸭属',
  'Netta': '潜鸭属',
  'Sarkidiornis': '瘤鸭属',
  'Alopochen': '埃及雁属',
  'Cairina': '栖鸭属',
  'Plectropterus': '距翅雁属',
  'Nettapus': '小棉凫属',
  'Phasianus': '雉属',
  'Lophura': '原鸡属',
  'Tragopan': '角雉属',
  'Syrmaticus': '长尾雉属',
  'Pavo': '孔雀属',
  'Gallus': '鸡属',
  'Coturnix': '鹌鹑属',
  'Perdix': '山鹑属',
  'Alectoris': '石鸡属',
  'Bambusicola': '竹鸡属',
  'Tetraophasis': '勺鸡属',
  'Tetrastes': '松鸡属',
  'Bonasa': '榛鸡属',
  'Rheinartia': '大眼斑雉属',
  'Polyplectron': '孔雀雉属',
  'Columba': '鸽属',
  'Streptopelia': '斑鸠属',
  'Spilopelia': '斑鸠属',
  'Ducula': '皇鸠属',
  'Macropygia': '鹃鸠属',
  'Geopelia': '姬地鸠属',
  'Zenaida': '哀鸽属',
  'Patagioenas': '美洲鸽属',
  'Leptotila': '哀鸽属',
  'Claravis': '蓝鸽属',
  'Metriopelia': '翅斑鸽属',
  'Uropelia': '草原鸽属',
  'Columbina': '姬鸽属',
  'Scardafella': '硬尾鸽属',
  'Egretta': '白鹭属',
  'Ardea': '鹭属',
  'Bubulcus': '牛背鹭属',
  'Casmerodius': '大白鹭属',
  'Mesophoyx': '中白鹭属',
  'Nycticorax': '夜鹭属',
  'Gorsachius': '绿鹭属',
  'Ixobrychus': '苇鳽属',
  'Botaurus': '大麻鳽属',
  'Syrigma': '苇鹭属',
  ' Tigriornis': '白颈鹭属',
  'Zebrilus': '林鳽属',
  'Cochlearius': '船鹭属',
  'Botaurus': '鳽属',
  'Ixobrychus': '苇鹭属',
  'Gorsachius': '绿鹭属',
  'Butorides': '池鹭属',
  'Dichromanassa': '黄嘴白鹭属',
  'Calherodius': '黑脸鹭属',
  'PNycticorax': '夜鹭属',
  'Pandion': '鹗属',
  'Milvus': '鸢属',
  'Haliaeetus': '海雕属',
  'Aquila': '雕属',
  'Clanga': '林雕属',
  'Ictinaetus': '林雕属',
  'Nisaetus': '蛇雕属',
  'Spizaetus': '鹰雕属',
  'Lophaetus': '冠雕属',
  'Stephanoaetus': '冕雕属',
  'Polemaetus': '吼雕属',
  'Circus': '鹞属',
  'Accipiter': '鹰属',
  'Buteo': '鵟属',
  'Falco': '隼属',
  'Tachybaptus': '小鸊鷉属',
  'Podiceps': '鸊鷉属',
  'Hydroprogne': '大凤头燕鸥属',
  'Chlidonias': '浮鸥属',
  'Sterna': '燕鸥属',
  'Gelochelidon': '凤头燕鸥属',
  'Hydroprogne': '巨嘴燕鸥属',
  'Thalasseus': '燕鸥属',
  'Alcedo': '翠鸟属',
  'Todiramphus': '林翡翠属',
  'Halcyon': '翡翠属',
  'Ceryle': '斑鱼狗属',
  'Megaceryle': '大鱼狗属',
  'Eurystomus': '佛法僧属',
  'Upupa': '戴胜属',
  'Buceros': '犀鸟属',
  'Anthracoceros': '斑犀鸟属',
  'Aceros': '无冠犀鸟属',
  'Ocyceros': '小犀鸟属',
  'Berenicornis': '白冠犀鸟属',
  'Rhinoploptera': '凹嘴犀鸟属',
  'Dryocopus': '黑啄木鸟属',
  'Picus': '绿啄木鸟属',
  'Dendrocopos': '啄木鸟属',
  'Dinopium': '金背啄木属',
  'Chrysocolaptes': '金背啄木属',
  'Bambus': '竹啄木属',
  'Sphyrapicus': '吸汁啄木属',
  'Melanerpes': '食虫啄木属',
  'Colaptes': '扑翅鴷属',
  'Cuculus': '杜鹃属',
  'Clamator': '噪鹃属',
  'Centropus': '鸦鹃属',
  'Eudynamys': '噪鹃属',
  'Surniculus': '乌鹃属',
  'Hierococcyx': '鹰鹃属',
  'Athene': '小鸮属',
  'Bubo': '雕鸮属',
  'Ketupa': '林鸮属',
  'Strix': '林鸮属',
  'Ninox': '鹰鸮属',
  'Glaucidium': '鸺鹠属',
  'Asio': '耳鸮属',
  'Otus': '角鸮属',
  'Tyto': '草鸮属',
  'Phodilus': '栗鸮属',
  'Apus': '雨燕属',
  'Hirundo': '燕属',
  'Delichon': '毛脚燕属',
  'Cecropis': '金腰燕属',
  'Petrochelidon': '烟腹燕属',
  'Pica': '喜鹊属',
  'Corvus': '鸦属',
  'Garrulus': '松鸦属',
  'Cyanopica': '灰喜鹊属',
  'Urocissa': '蓝鹊属',
  'Cissa': '绿鹊属',
  'Perisoreus': '山鸦属',
  'Nucifraga': '星鸦属',
  'Pyrrhocorax': '山鸦属',
  'Temnurus': '塔尾树鹊属',
  'Crypsirina': '树鹊属',
  'Hypothymis': '黑枕王鹟属',
  'Terpsiphone': '寿带属',
  'Lanius': '伯劳属',
  'Oriolus': '黄鹂属',
  'Dicrurus': '卷尾属',
  'Sturnus': '椋鸟属',
  'Acridotheres': '八哥属',
  'Gracupica': '喜鹊椋鸟属',
  'Pastor': '粉红椋鸟属',
  'Spodiopsar': '灰椋鸟属',
  'Agropsar': '北椋鸟属',
  'Sturnia': '林椋鸟属',
  'Passer': '雀属',
  'Motacilla': '鹡鸰属',
  'Anthus': '鹨属',
  'Alauda': '百灵属',
  'Galerida': '凤头百灵属',
  'Melanocorypha': '百灵属',
  'Calandrella': '沙百灵属',
  'Eremopterix': '斑翅百灵属',
  'Ammomanes': '漠百灵属',
  'Certila': '歌百灵属',
  'Carduelis': '金翅雀属',
  'Serinus': '金丝雀属',
  'Chloris': '绿金翅属',
  'Acanthis': '红额金翅属',
  'Loxia': '交嘴雀属',
  'Pyrrhula': '松雀属',
  'Coccothraustes': '锡嘴雀属',
  'Eophona': '蜡嘴雀属',
  'Haematortyx': '血翅鹑属',
  'Lophophanes': '凤头山雀属',
  'Poecile': '黑顶山雀属',
  'Periparus': '煤山雀属',
  'Cyanistes': '青山雀属',
  'Parus': '山雀属',
  'Aegithalos': '长尾山雀属',
  'Sitta': '鳾属',
  'Certhia': '旋木雀属',
  'Troglodytes': '鹪鹩属',
  'Prunella': '岩鹨属',
  'Regulus': '戴菊属',
  'Muscicapa': '鹟属',
  'Ficedula': '姬鹟属',
  'Cyanoptila': '白鹟属',
  'Eumyias': '纯色鹟属',
  'Monticola': '石鹟属',
  'Myrmus': '林鹟属',
  'Turdus': '鸫属',
  'Saxicola': '石鹟属',
  'Oenanthe': '石栖鹟属',
  'Cisticola': '扇尾莺属',
  'Prinia': '缝叶莺属',
  'Locustella': '草莺属',
  'Acrocephalus': '苇莺属',
  'Hippolais': '篱莺属',
  'Sylvia': '林莺属',
  'Phylloscopus': '柳莺属',
  'Seicercus': '柳莺属',
  'Abroscopus': '山鹛属',
  'Leptopoecile': ' alpine warbler属',
  'Megalurus': '大苇莺属',
  'Rhipidura': '扇尾鹟属',
  'Myiagra': '阔嘴鹟属',
  'Grus': '鹤属',
  'Anthropoides': '蓑羽鹤属',
  'Bugeranus': '肉垂鹤属',
  'Fulica': '骨顶属',
  'Gallinula': '黑水鸡属',
  'Porphyrio': '紫水鸡属',
  'Amaurornis': '苦恶鸟属',
  'Zapornia': '田鸡属',
  'Gallicrex': '董鸡属',
  'Coturnix': '鹌鹑属',
  'Turnix': '三趾鹑属',
  'Vanellus': '凤头麦鸡属',
  'Pluvialis': '斑鸻属',
  'Charadrius': '鸻属',
  'Eudromias': '燕鸻属',
  'Oreopholus': '冠鸻属',
  'Actitis': '矶鹬属',
  'Tringa': '鹬属',
  'Scolopax': '沙锥属',
  'Gallinago': '扇尾沙锥属',
  'Limosa': '滕鹬属',
  'Numenius': '杓鹬属',
  'Heteroscelus': '漂鹬属',
  'Phalaropus': '瓣蹼鹬属',
  'Calidris': '滨鹬属',
  'Limicola': '阔嘴鹬属',
  'Philomachus': '流苏鹬属',
  'Larus': '鸥属',
  'Chroicocephalus': '彩头鸥属',
  'Hydrocoloeus': '小鸥属',
  'Ichthyaetus': '玉筋鸥属',
  'Rissa': '三趾鸥属',
  'Pagophila': '玉鸥属',
  'Xema': '楔尾鸥属',
  'Creagrus': '钩嘴鸥属',
  'Rhodostethia': '楔喙鸥属',
  'Rousettus': '果蝠属',
  'Myrmecophaga': '食蚁兽属',
  'Tamandua': '小食蚁兽属',
  'Cyclopes': '丝食蚁兽属',
};

function translateOrder(order: string | null): string | null {
  if (!order) return null;
  return orderMap[order] || null;
}

function translateFamily(family: string | null): string | null {
  if (!family) return null;
  return familyMap[family] || null;
}

function extractGenus(scientificName: string): string | null {
  const parts = scientificName.trim().split(/\s+/);
  if (parts.length < 2) return null;
  const genus = parts[0];
  const genusLower = genus.toLowerCase();
  for (const [lat, cn] of Object.entries(genusMap)) {
    if (lat.toLowerCase() === genusLower) {
      return cn;
    }
  }
  return null;
}

const ebirdData: Record<string, unknown>[] = JSON.parse(readFileSync('D:/Code/Bird/server/data/ebird_species.json', 'utf-8'));

console.log('Processing', ebirdData.length, 'species...');

const result = ebirdData.map((sp) => {
  return {
    ...sp,
    orderName: translateOrder(sp.orderName as string),
    familyName: translateFamily(sp.familyName as string),
    genus: extractGenus(sp.scientificName as string),
  };
});

const missingOrder = result.filter(r => !r.orderName).length;
const missingFamily = result.filter(r => !r.familyName).length;
const missingGenus = result.filter(r => !r.genus).length;
console.log(`Missing: order=${missingOrder}, family=${missingFamily}, genus=${missingGenus}`);
console.log('Sample (first 5):');
for (const r of result.slice(0, 5)) {
  console.log(`  ${r.chineseName} | ${r.scientificName} | 目:${r.orderName} | 科:${r.familyName} | 属:${r.genus}`);
}

writeFileSync('D:/Code/Bird/server/data/ebird_species_enriched.json', JSON.stringify(result, null, 2), 'utf-8');
console.log('Saved to ebird_species_enriched.json');
